
package bankservicewsdl;

import java.math.BigInteger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "bankservicewsdlPortType", targetNamespace = "urn:bankservicewsdl")
@SOAPBinding(style = SOAPBinding.Style.RPC)
public interface BankservicewsdlPortType {


    /**
     * Kijk of de klant genoeg saldo heeft.
     * 
     * @param amount
     * @param accountnr
     * @return
     *     returns boolean
     */
    @WebMethod(action = "urn:bankservicewsdl#doCreditCheck")
    @WebResult(partName = "return")
    public boolean doCreditCheck(
        @WebParam(name = "accountnr", partName = "accountnr")
        BigInteger accountnr,
        @WebParam(name = "amount", partName = "amount")
        double amount);

    /**
     * Boek geld over van de eerste naar de tweede rekening.
     * 
     * @param amount
     * @param pin
     * @param accountto
     * @param accountfrom
     * @return
     *     returns boolean
     */
    @WebMethod(action = "urn:bankservicewsdl#transfer")
    @WebResult(partName = "return")
    public boolean transfer(
        @WebParam(name = "accountfrom", partName = "accountfrom")
        BigInteger accountfrom,
        @WebParam(name = "accountto", partName = "accountto")
        BigInteger accountto,
        @WebParam(name = "amount", partName = "amount")
        double amount,
        @WebParam(name = "pin", partName = "pin")
        BigInteger pin);

}
